//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSS_SyncFile
{
    using Model;
    using System;
    using System.Collections.Generic;

    public class Profile
    {
        public int Id { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
        
        /*
        public string cnpj { get; set; }
        public string diretorio { get; set; }
        */
        
        public Boolean startSO { get; set; }
        public string instalacao { get; set; }

        public string versaoApp { get; set; }

        public List<DocssDirectory> listDocssDirectory { get; set; }
        

        public int maxArqMin { get; set; }

        public string server { get; set; }
    }

   
}
