//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSS_SyncFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_ARQ_ENV
    {
        public int Id { get; set; }
        public string NOME_ARQ { get; set; }
        public string EXTENSAO_ARQ { get; set; }
        public Nullable<int> TAMANHO_ARQ { get; set; }
        public string LOCAL_ORIG_ARQ { get; set; }
        public Nullable<System.DateTime> DATA_ENV_ARQ { get; set; }
        public string USUARIO { get; set; }
        public Nullable<decimal> CNPJ_ENV { get; set; }
        public string COD_INSTALACAO { get; set; }
        public string STATUS_ENV { get; set; }
    }
}
